twig:
    form_themes:
        - 'LexikFormFilterBundle:Form:form_div_layout.html.twig'
        - 'MWSimpleAdminCrudBundle:Form:mws_vich_fields.html.twig'
        - 'MWSimpleAdminCrudBundle:Form:fields.html.twig'
        - 'MWSimpleAdminCrudBundle:Form:select2entity_type.html.twig'
        - 'MWSimpleAdminCrudBundle:Form:duallist_type.html.twig'

sc_datetimepicker:
    picker: ~

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb_list:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
