twig:
    form_themes:
        - 'MWSimpleAdminCrudBundle:Form:fields.html.twig'
        - 'LexikFormFilterBundle:Form:form_div_layout.html.twig'
        - 'MWSimpleAdminCrudBundle:Form:select2entity_type.html.twig'
        - 'MWSimpleAdminCrudBundle:Form:duallist_field.html.twig'
        - 'MWSimpleAdminCrudBundle:Form:field_file.html.twig'

sc_datetimepicker:
    picker: ~

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

#Services pasando a services.xml
services:
    form.type.duallist:
        class: MWSimple\Bundle\AdminCrudBundle\Form\Type\DualListType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: duallist }
    form.type.mwspeso:
        class: MWSimple\Bundle\AdminCrudBundle\Form\Type\PesoType
        tags:
            - { name: form.type, alias: mwspeso }
    mws_field_file_type:
        class: MWSimple\Bundle\AdminCrudBundle\Form\Type\FieldFileType
        tags:
            - { name: form.type, alias: mws_field_file }